[package]
name = "mrpack-container"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
url = { version = "2.3.1", features = ["serde"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
hex = { version = "0.4.2", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zip = "0.6.3"
anyhow = "1.0.68"
oci-spec = "0.5.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1.24.2", features = ["full"] }
thiserror = "1.0.38"
futures-util = "0.3.25"
rust-crypto = "0.2.36"
tempfile = "3.3.0"
bytes = "1.4.0"
dkregistry = "0.5.0"
regex = "1.10.2"
